name: First Workflow

on: [push]
# defaults:
#     run:
#         shell: bash
#         working-directory: /de/de
jobs:
  run-shell-commands:
    runs-on: ubuntu-latest
    steps:
        - name: echo a string
          run: echo "Hello World"
        - name: Multiline Command
          run: |
            node -v
            npm -v
  parallel-job-macos:
    runs-on: macos-latest
    steps:
        - name: View SW version
          run: sw_vers
  dependant-job:
    runs-on: windows-latest
    needs: run-shell-commands
    steps:
        - name: echo a string
          run: Write-Output "Windows strings"
        - name: setting an error message
          run: echo "::error::Missing Semicolon"
        - name: Setting an error msg with params
          run: echo "::error::msg"
  display-wd-info-ubuntu:
    runs-on: ubuntu-latest
    steps:
        - name: Disply
          run: |
            pwd
            ls -a
            echo $GITHUB_SHA
            echo $GITHUB_RESPOSITORY
            echo $GITHUB_WORKSPACE
        - name: Change Working Dir
          working-directory: /home/runner
          run: pwd   
  display-wd-info-windows:
    runs-on: windows-latest
    defaults:
        run:
            shell: pwsh
    steps:
        - name: Disply
          run: |
            Get-Location
            dir
            echo $env:GITHUB_SHA
            echo $env:GITHUB_RESPOSITORY
            echo $env:GITHUB_WORKSPACE 
        - name: Python Shell
          shell: python
          run: |
            import platform
            print(platform.processor())