name: Checkout
on: [push]
jobs:
    simple-action:
        runs-on: ubuntu-latest
        steps:
            - name: List Files Before
              uses: actions/hello-world-javascript-action@main
              with:
                who-to-greet: Sunil
            - name: Log Greeting Time
              run: echo "${{ steps.greet.Output.Time }}"